language: python
python:
- '3.5'
script:
- flake8 .
- bandit -r .
deploy:
  provider: pypi
  user: briggsb
  password:
    secure: HThgSx5LsnGWDUZ/UPyROVrZP3u2vfXt3jI5hb6Szpav+bF53bReFOrqeME8OKCwwy7+Jjy389E7bmfbxdUpF35sqNfDfdLNz/7F3WnsqeiPL2QgxTDoEN6aTQhM/snqyRgwfaqD8ym7wEikAEy4BFVvvKb9VJ2DLEb/dkQw3TpsLAD12EcQrvujZcz4msC0iDP60JQ/h1KldSkzNvSOu9Ek1veq2daL2Tf5aAGUv0jFB8L0IhCnGdlYVpQWDIs4k9HS3FbhkqKgX55Lk1sHBJ5iKS1ym8qkaACZdICq1Ko9gwZjgI07spKt99gccBIFrKvvd9SUAmNO5+8sGxqpv4+pF2wKilO3sQtni+i7e3oZEyYzKe7w5zpxH6YofW/lR9EY7l0n4tkJ38awUIDOynETr2BOZcqMAS8sYbJj3rix0Lnc5cVS8u+9ge1f2I3n1NUyP756+A8ArYpoKPTbpICm8SVB1Wx7hRNrkNtuQ0HFDLSzlvxVTH0/BE8ru9DeLXpHNQ8sb92Gccspc6LrqMFnNeU4xEduWMWiEkEncSNS+f5E+KOC0spEyNO8bkimZxpZsCxijsV7R0nCA7/oTpyou6vDUR3vXL+tkrsDIvuIf6nF1j1boQpW9xiULQsfsnim6VIu4QGznrwhddZ0KGQxYMnpnbvEauA/5cKHtCA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bbriggs/legos.xkcd
